package craftapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// RenderPowerShell renders the spec as a complete, runnable PowerShell 7
// script that performs all wiring calls against the Veeam REST API.
func RenderPowerShell(s Spec) (string, error) {
	applyDefaults(&s)
	steps := Plan(s)

	var b strings.Builder

	// Header block.
	b.WriteString("# ===========================================================================\n")
	b.WriteString("# Veeam Backup & Replication – Automated Wiring Script (PowerShell 7)\n")
	b.WriteString("# Generated by autodeploy-web craftapi — render-only, edit before running.\n")
	b.WriteString("#\n")
	b.WriteString("# WARNING: This script skips TLS certificate verification (-SkipCertificateCheck)\n")
	b.WriteString("# and transmits credentials in plain HTTP headers over your LAN/management\n")
	b.WriteString("# network. Use only in trusted, air-gapped or firewalled environments.\n")
	if s.License {
		b.WriteString("#\n")
		b.WriteString("# LICENSE NOTE:\n")
		b.WriteString("#   The license body must be the base64 encoding of your .lic file.\n")
		b.WriteString("#   To obtain it in PowerShell:\n")
		b.WriteString("#     [Convert]::ToBase64String([IO.File]::ReadAllBytes('veeam.lic'))\n")
		if s.LicenseB64 == "" {
			b.WriteString("#   The placeholder <BASE64_OF_YOUR_LIC> below must be replaced before running.\n")
		}
	}
	b.WriteString("# ===========================================================================\n\n")

	// Preamble — base URL + credentials.
	baseURL := s.BaseURL
	if baseURL == "" {
		baseURL = "https://<VSA_IP>:9419"
	}
	fmt.Fprintf(&b, "$BaseURL    = %q\n", baseURL)
	fmt.Fprintf(&b, "$Username   = %q\n", s.Username)
	// Password as single-quoted to be literal-safe (no $ expansion risk).
	fmt.Fprintf(&b, "$Password   = '%s'\n", strings.ReplaceAll(s.Password, "'", "''"))
	fmt.Fprintf(&b, "$APIVersion = %q\n", s.APIVersion)

	// Secret preamble variables — single-quoted, literal-safe.
	if s.S3.Enabled {
		fmt.Fprintf(&b, "$S3AccessKey = '%s'\n", strings.ReplaceAll(s.S3.AccessKey, "'", "''"))
		fmt.Fprintf(&b, "$S3SecretKey = '%s'\n", strings.ReplaceAll(s.S3.SecretKey, "'", "''"))
	}
	if s.NodeExporter && s.NodeExporterUser != "" {
		fmt.Fprintf(&b, "$NeBasicPass = '%s'\n", strings.ReplaceAll(s.NodeExporterPass, "'", "''"))
	}
	b.WriteString("\n")

	// Connect-Vbr (re)acquires a bearer token and refreshes $script:Headers.
	// Wiring can run longer than the token's lifetime, so every call goes through
	// Invoke-Vbr which re-authenticates and retries once on HTTP 401.
	b.WriteString("# ---------------------------------------------------------------------------\n")
	b.WriteString("# Auth helpers — token auto-refresh on 401 (wiring can outlive the token).\n")
	b.WriteString("# ---------------------------------------------------------------------------\n")
	b.WriteString("function Connect-Vbr {\n")
	b.WriteString("    $r = Invoke-RestMethod -SkipCertificateCheck `\n")
	b.WriteString("        -Method POST `\n")
	b.WriteString("        -Uri \"$BaseURL/api/oauth2/token\" `\n")
	b.WriteString("        -Headers @{ 'x-api-version' = $APIVersion; 'Accept' = 'application/json' } `\n")
	b.WriteString("        -ContentType 'application/x-www-form-urlencoded' `\n")
	b.WriteString("        -Body \"grant_type=Password&username=$Username&password=$Password\"\n")
	b.WriteString("    $script:Headers = @{\n")
	b.WriteString("        'x-api-version' = $APIVersion\n")
	b.WriteString("        'Accept'        = 'application/json'\n")
	b.WriteString("        'Authorization' = \"Bearer $($r.access_token)\"\n")
	b.WriteString("    }\n")
	b.WriteString("}\n\n")

	b.WriteString("function Invoke-Vbr {\n")
	b.WriteString("    param([string]$Method, [string]$Uri, $Body)\n")
	b.WriteString("    $p = @{ SkipCertificateCheck = $true; Method = $Method; Uri = $Uri; Headers = $script:Headers }\n")
	b.WriteString("    if ($null -ne $Body) { $p.ContentType = 'application/json'; $p.Body = $Body }\n")
	b.WriteString("    try { return Invoke-RestMethod @p }\n")
	b.WriteString("    catch {\n")
	b.WriteString("        if ($_.Exception.Response.StatusCode.value__ -eq 401) {\n")
	b.WriteString("            Write-Host '    (token expired — re-authenticating)'\n")
	b.WriteString("            Connect-Vbr\n")
	b.WriteString("            $p.Headers = $script:Headers\n")
	b.WriteString("            return Invoke-RestMethod @p\n")
	b.WriteString("        }\n")
	b.WriteString("        throw\n")
	b.WriteString("    }\n")
	b.WriteString("}\n\n")

	// Wait-for-session helper (uses Invoke-Vbr → re-auths on 401 mid-wait).
	b.WriteString("function Wait-VbrSession {\n")
	b.WriteString("    param([string]$SessionId, [int]$PollSeconds = 10, [int]$TimeoutSeconds = 1800)\n")
	b.WriteString("    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)\n")
	b.WriteString("    do {\n")
	b.WriteString("        Start-Sleep -Seconds $PollSeconds\n")
	b.WriteString("        $s = Invoke-Vbr -Method GET -Uri \"$BaseURL/api/v1/sessions/$SessionId\"\n")
	b.WriteString("        if ($s.result.result -eq 'Failed') { throw \"Session $SessionId failed\" }\n")
	b.WriteString("        if ($s.result.result -in 'Success','Warning') { return }\n")
	b.WriteString("        if ($s.state -eq 'Stopped') { return }\n")
	b.WriteString("    } while ((Get-Date) -lt $deadline)\n")
	b.WriteString("    throw \"Session $SessionId did not finish within $TimeoutSeconds seconds\"\n")
	b.WriteString("}\n\n")

	// VIA-node wiring helpers — Wait-VbrNode, Find-VbrManagedServer, Find-VbrRepository,
	// Get-VbrFingerprint, Update-VbrComponents, Register-ViaHost, New-VbrHardenedRepo,
	// New-VbrProxy. These mirror the per-node control flow in internal/wiring/wiring.go
	// (waitNodeUp, FindManagedServerByName, FindRepositoryByName, createWithComponents)
	// and the JSON bodies in internal/veeam/veeam.go (AddLinuxHost, AddHardenedRepository,
	// AddVmwareProxy). Invoke-WithComponents is inlined into the create funcs to avoid
	// scriptblock-scoping issues.
	b.WriteString("function Wait-VbrNode {\n")
	b.WriteString("    param([string]$Ip, [int]$TimeoutSeconds = 1800)\n")
	b.WriteString("    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)\n")
	b.WriteString("    while ((Get-Date) -lt $deadline) {\n")
	b.WriteString("        foreach ($p in 6160,443,22) {\n")
	b.WriteString("            try { $c = [Net.Sockets.TcpClient]::new(); $c.Connect($Ip,$p); $c.Close(); return } catch { }\n")
	b.WriteString("        }\n")
	b.WriteString("        Write-Host \"    ...$Ip still installing/booting\"\n")
	b.WriteString("        Start-Sleep -Seconds 15\n")
	b.WriteString("    }\n")
	b.WriteString("    throw \"Node $Ip not reachable within $TimeoutSeconds seconds\"\n")
	b.WriteString("}\n")
	b.WriteString("function Find-VbrManagedServer {\n")
	b.WriteString("    param([string]$Ip)\n")
	b.WriteString("    $r = Invoke-Vbr -Method GET -Uri \"$BaseURL/api/v1/backupInfrastructure/managedServers?nameFilter=$Ip&limit=10\"\n")
	b.WriteString("    ($r.data | Where-Object { $_.name -eq $Ip } | Select-Object -First 1).id\n")
	b.WriteString("}\n")
	b.WriteString("function Find-VbrRepository {\n")
	b.WriteString("    param([string]$Name)\n")
	b.WriteString("    $r = Invoke-Vbr -Method GET -Uri \"$BaseURL/api/v1/backupInfrastructure/repositories?nameFilter=$Name&limit=50\"\n")
	b.WriteString("    ($r.data | Where-Object { $_.name -eq $Name } | Select-Object -First 1).id\n")
	b.WriteString("}\n")
	b.WriteString("function Get-VbrFingerprint {\n")
	b.WriteString("    param([string]$Ip)\n")
	b.WriteString("    $body = @{ serverName = $Ip; type = 'LinuxHost' } | ConvertTo-Json\n")
	b.WriteString("    $r = Invoke-Vbr -Method POST -Uri \"$BaseURL/api/v1/connectionCertificate\" -Body $body\n")
	b.WriteString("    [BitConverter]::ToString([System.Security.Cryptography.SHA256]::HashData([Convert]::FromBase64String($r.certificateUpload.certificate))).Replace('-','')\n")
	b.WriteString("}\n")
	b.WriteString("function Update-VbrComponents {\n")
	b.WriteString("    param([string]$HostId)\n")
	b.WriteString("    Write-Host '    host components are updating - re-running update and retrying'\n")
	b.WriteString("    try { $u = Invoke-Vbr -Method POST -Uri \"$BaseURL/api/v1/backupInfrastructure/managedServers/updateComponents\" -Body (@{ ids = @($HostId) } | ConvertTo-Json); Wait-VbrSession -SessionId $u.id } catch { }\n")
	b.WriteString("}\n")
	b.WriteString("function Register-ViaHost {\n")
	b.WriteString("    param([string]$Ip, [string]$Role, [string]$Pairing)\n")
	b.WriteString("    $id = Find-VbrManagedServer -Ip $Ip\n")
	b.WriteString("    if ($id) { Write-Host \"    $Ip already registered - skipping add\"; return $id }\n")
	b.WriteString("    Write-Host \"    adding Linux host $Ip\"\n")
	b.WriteString("    $fp = Get-VbrFingerprint -Ip $Ip\n")
	b.WriteString("    $body = @{ type = 'LinuxHost'; name = $Ip; description = $Role; credentialsStorageType = 'Certificate'; handshakeCode = $Pairing; sshFingerprint = $fp } | ConvertTo-Json\n")
	b.WriteString("    $r = Invoke-Vbr -Method POST -Uri \"$BaseURL/api/v1/backupInfrastructure/managedServers\" -Body $body\n")
	b.WriteString("    Wait-VbrSession -SessionId $r.id\n")
	b.WriteString("    $id = Find-VbrManagedServer -Ip $Ip\n")
	b.WriteString("    if (-not $id) { throw \"Failed to resolve managed server $Ip after add\" }\n")
	b.WriteString("    return $id\n")
	b.WriteString("}\n")
	b.WriteString("function New-VbrHardenedRepo {\n")
	b.WriteString("    param([string]$HostId, [string]$Name, [string]$Path, [int]$ImmutableDays)\n")
	b.WriteString("    $id = Find-VbrRepository -Name $Name\n")
	b.WriteString("    if ($id) { Write-Host \"    repository $Name already exists - skipping\"; return $id }\n")
	b.WriteString("    Write-Host \"    creating hardened repository $Name\"\n")
	b.WriteString("    $body = @{ type = 'LinuxHardened'; name = $Name; description = ''; hostId = $HostId; repository = @{ path = $Path; useFastCloningOnXFSVolumes = $true; makeRecentBackupsImmutableDays = $ImmutableDays } } | ConvertTo-Json -Depth 12\n")
	b.WriteString("    for ($a = 1; $a -le 3; $a++) {\n")
	b.WriteString("        try { $r = Invoke-Vbr -Method POST -Uri \"$BaseURL/api/v1/backupInfrastructure/repositories\" -Body $body; Wait-VbrSession -SessionId $r.id; break }\n")
	b.WriteString("        catch {\n")
	b.WriteString("            $m = \"$($_.ErrorDetails.Message) $($_.Exception.Message)\"\n")
	b.WriteString("            if ($a -lt 3 -and $m -like '*pending components update*') { Update-VbrComponents -HostId $HostId; continue }\n")
	b.WriteString("            throw\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n")
	b.WriteString("    return (Find-VbrRepository -Name $Name)\n")
	b.WriteString("}\n")
	b.WriteString("function New-VbrProxy {\n")
	b.WriteString("    param([string]$HostId)\n")
	b.WriteString("    Write-Host '    registering VMware backup proxy'\n")
	b.WriteString("    $body = @{ type = 'ViProxy'; description = ''; server = @{ hostId = $HostId; maxTaskCount = 4 } } | ConvertTo-Json -Depth 12\n")
	b.WriteString("    for ($a = 1; $a -le 3; $a++) {\n")
	b.WriteString("        try { $r = Invoke-Vbr -Method POST -Uri \"$BaseURL/api/v1/backupInfrastructure/proxies\" -Body $body; Wait-VbrSession -SessionId $r.id; break }\n")
	b.WriteString("        catch {\n")
	b.WriteString("            $m = \"$($_.ErrorDetails.Message) $($_.Exception.Message)\"\n")
	b.WriteString("            if ($a -lt 3 -and $m -like '*pending components update*') { Update-VbrComponents -HostId $HostId; continue }\n")
	b.WriteString("            throw\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n")
	b.WriteString("}\n\n")

	b.WriteString("Write-Host '==> Authenticating'\n")
	b.WriteString("Connect-Vbr\n\n")

	// Render each step.
	for _, st := range steps {
		if err := renderPowerShellStep(&b, st); err != nil {
			return "", err
		}
	}

	b.WriteString("Write-Host '==> Done.'\n")
	return b.String(), nil
}

// psEcho emits a Write-Host progress line for a step comment (single-quoted,
// apostrophe-escaped, no $ expansion).
func psEcho(b *strings.Builder, comment string) {
	fmt.Fprintf(b, "Write-Host '==> %s'\n", strings.ReplaceAll(comment, "'", "''"))
}

func renderPowerShellStep(b *strings.Builder, st Step) error {
	b.WriteString("# ---------------------------------------------------------------------------\n")
	b.WriteString("# " + st.Comment + "\n")
	b.WriteString("# ---------------------------------------------------------------------------\n")

	// High-level VIA-node wiring steps — delegate to helper functions.
	if st.Kind == "wireViaHr" {
		return renderPSWireViaHr(b, st)
	}
	if st.Kind == "wireViaProxy" {
		return renderPSWireViaProxy(b, st)
	}

	psEcho(b, st.Comment)

	// configBackupRedirect is a special read-modify-write step.
	if st.Kind == "configBackupRedirect" {
		return renderPSConfigBackupRedirect(b, st)
	}

	switch st.Method {
	case "GET", "DELETE":
		path := psExpandPath(st.Path)
		fmt.Fprintf(b, "$resp = Invoke-Vbr -Method %s -Uri \"%s%s\"\n", st.Method, "$BaseURL", path)

	case "POST", "PUT":
		path := psExpandPath(st.Path)
		b.WriteString("$body = ")
		if st.Body != nil {
			bodyStr, err := psValue(st.Body)
			if err != nil {
				return fmt.Errorf("psValue body for %s %s: %w", st.Method, st.Path, err)
			}
			b.WriteString(bodyStr)
			b.WriteString(" | ConvertTo-Json -Depth 12\n")
		} else {
			b.WriteString("'{}'\n")
		}
		fmt.Fprintf(b, "$resp = Invoke-Vbr -Method %s -Uri \"%s%s\" -Body $body\n", st.Method, "$BaseURL", path)
	}

	// Extract captures from $resp.
	if st.Kind == "certFingerprint" {
		// The API returns a certificate, not a fingerprint; compute SHA-256
		// (uppercase hex) of the decoded cert, matching veeam.ConnectionCertificate.
		fmt.Fprintf(b, "$%s = [BitConverter]::ToString([System.Security.Cryptography.SHA256]::HashData([Convert]::FromBase64String($resp.certificateUpload.certificate))).Replace('-','')\n", st.Captures[0].Var)
	} else {
		for _, cap := range st.Captures {
			expr := psCapExpr(cap.Expr)
			fmt.Fprintf(b, "$%s = $resp%s\n", cap.Var, expr)
		}
	}

	// Wait for async session.
	if st.WaitSession && st.WaitVar != "" {
		if st.OptionalWait {
			fmt.Fprintf(b, "try { Wait-VbrSession -SessionId $%s } catch { Write-Warning \"optional step did not complete (continuing): $_\" }\n", st.WaitVar)
		} else {
			fmt.Fprintf(b, "Wait-VbrSession -SessionId $%s\n", st.WaitVar)
		}
	}

	b.WriteString("\n")
	return nil
}

// renderPSWireViaHr emits the high-level HR-node wiring block using the
// helper functions defined in the script preamble.
func renderPSWireViaHr(b *strings.Builder, st Step) error {
	fmt.Fprintf(b, "Write-Host '==> Wire %s %s'\n", strings.ReplaceAll(st.Role, "'", "''"), st.IP)
	fmt.Fprintf(b, "Wait-VbrNode -Ip '%s'\n", st.IP)
	fmt.Fprintf(b, "$%s = Register-ViaHost -Ip '%s' -Role '%s' -Pairing '%s'\n",
		st.HostVar, st.IP,
		strings.ReplaceAll(st.Role, "'", "''"),
		strings.ReplaceAll(st.Pairing, "'", "''"))
	fmt.Fprintf(b, "$%s = New-VbrHardenedRepo -HostId $%s -Name '%s' -Path '%s' -ImmutableDays %d\n",
		st.RepoVar, st.HostVar,
		strings.ReplaceAll(st.RepoName, "'", "''"),
		strings.ReplaceAll(st.RepoPath, "'", "''"),
		st.ImmutableDays)
	b.WriteString("\n")
	return nil
}

// renderPSWireViaProxy emits the high-level proxy-node wiring block using the
// helper functions defined in the script preamble.
func renderPSWireViaProxy(b *strings.Builder, st Step) error {
	fmt.Fprintf(b, "Write-Host '==> Wire %s %s'\n", strings.ReplaceAll(st.Role, "'", "''"), st.IP)
	fmt.Fprintf(b, "Wait-VbrNode -Ip '%s'\n", st.IP)
	fmt.Fprintf(b, "$%s = Register-ViaHost -Ip '%s' -Role '%s' -Pairing '%s'\n",
		st.HostVar, st.IP,
		strings.ReplaceAll(st.Role, "'", "''"),
		strings.ReplaceAll(st.Pairing, "'", "''"))
	fmt.Fprintf(b, "New-VbrProxy -HostId $%s\n", st.HostVar)
	b.WriteString("\n")
	return nil
}

// renderPSConfigBackupRedirect emits the read-modify-write pattern for
// /api/v1/configBackup. It GETs the current settings, patches
// backupRepositoryId + notifications.SNMPEnabled=false, then PUTs back.
func renderPSConfigBackupRedirect(b *strings.Builder, st Step) error {
	repoIDExpr := "$repo0_id"
	if m, ok := st.Body.(map[string]any); ok {
		if v, ok2 := m["backupRepositoryId"].(string); ok2 {
			repoIDExpr = v
		}
	}
	repoIDExpanded := psExpandPath(repoIDExpr)

	b.WriteString("$cfg = Invoke-Vbr -Method GET -Uri \"$BaseURL/api/v1/configBackup\"\n")
	fmt.Fprintf(b, "$cfg.backupRepositoryId = \"%s\"\n", repoIDExpanded)
	b.WriteString("if ($cfg.notifications) { $cfg.notifications.SNMPEnabled = $false }\n")
	b.WriteString("$body = $cfg | ConvertTo-Json -Depth 30\n")
	b.WriteString("$resp = Invoke-Vbr -Method PUT -Uri \"$BaseURL/api/v1/configBackup\" -Body $body\n")
	b.WriteString("\n")
	return nil
}

// psExpandPath converts $var_id style references in a path string so they
// expand inside a PowerShell double-quoted string. The references are already
// valid PS variable syntax ($ident) so no transformation is needed.
func psExpandPath(path string) string {
	return path
}

// psCapExpr converts a jq-style capture expression like "data[0].id" or
// "certificateUpload.certificate" to a PowerShell member-access chain like
// ".data[0].id".  A leading "." is added; array subscripts are kept.
// The special value "__object__" returns "" (the whole object).
func psCapExpr(expr string) string {
	if expr == "__object__" || expr == "" {
		return ""
	}
	return "." + expr
}

// psValue converts a Go value to a PowerShell literal.
//
//   - string matching ^$[A-Za-z_][A-Za-z0-9_]*(.[A-Za-z_][A-Za-z0-9_]*|\[[0-9]+\])*$
//     → emitted bare (variable/expression, expands in double-quoted context)
//   - any other string → single-quoted with apostrophe escaped as double-apostrophe
//   - bool → $true / $false
//   - json.Number / int / float64 → bare numeric literal
//   - map[string]any → @{ 'k' = v ... } with sorted keys
//   - []any / []string → @( v, ... )
func psValue(v any) (string, error) {
	switch val := v.(type) {
	case string:
		if isPSVarExpr(val) {
			return val, nil
		}
		return "'" + strings.ReplaceAll(val, "'", "''") + "'", nil
	case bool:
		if val {
			return "$true", nil
		}
		return "$false", nil
	case json.Number:
		return val.String(), nil
	case int:
		return itoa(val), nil
	case float64:
		return fmt.Sprintf("%g", val), nil
	case map[string]any:
		return psHashtable(val)
	case []any:
		return psArray(val)
	case []string:
		items := make([]any, len(val))
		for i, s := range val {
			items[i] = s
		}
		return psArray(items)
	case nil:
		return "$null", nil
	default:
		b, err := json.Marshal(val)
		if err != nil {
			return "", err
		}
		return "'" + strings.ReplaceAll(string(b), "'", "''") + "'", nil
	}
}

// isPSVarExpr returns true if s is a PowerShell variable reference that is
// safe to emit bare. Pattern: $ident optionally followed by .member or [n] chains.
func isPSVarExpr(s string) bool {
	if len(s) < 2 || s[0] != '$' {
		return false
	}
	i := 1
	if !isAlpha(s[i]) && s[i] != '_' {
		return false
	}
	i++
	for i < len(s) {
		c := s[i]
		if isAlpha(c) || isDigit(c) || c == '_' {
			i++
			continue
		}
		if c == '.' {
			i++
			if i >= len(s) || (!isAlpha(s[i]) && s[i] != '_') {
				return false
			}
			for i < len(s) && (isAlpha(s[i]) || isDigit(s[i]) || s[i] == '_') {
				i++
			}
			continue
		}
		if c == '[' {
			i++
			start := i
			for i < len(s) && isDigit(s[i]) {
				i++
			}
			if i == start || i >= len(s) || s[i] != ']' {
				return false
			}
			i++
			continue
		}
		return false
	}
	return true
}

func psHashtable(m map[string]any) (string, error) {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("@{\n")
	for _, k := range keys {
		vStr, err := psValue(m[k])
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&sb, "    '%s' = %s\n", k, vStr)
	}
	sb.WriteString("}")
	return sb.String(), nil
}

func psArray(items []any) (string, error) {
	if len(items) == 0 {
		return "@()", nil
	}
	parts := make([]string, len(items))
	for i, item := range items {
		v, err := psValue(item)
		if err != nil {
			return "", err
		}
		parts[i] = v
	}
	return "@( " + strings.Join(parts, ", ") + " )", nil
}

// RenderCurl renders the spec as a complete, runnable bash+jq script using curl.
func RenderCurl(s Spec) (string, error) {
	applyDefaults(&s)
	steps := Plan(s)

	var b strings.Builder

	// Header block.
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# ===========================================================================\n")
	b.WriteString("# Veeam Backup & Replication – Automated Wiring Script (bash + curl + jq)\n")
	b.WriteString("# Generated by autodeploy-web craftapi — render-only, edit before running.\n")
	b.WriteString("#\n")
	b.WriteString("# WARNING: This script skips TLS verification (curl -k) and transmits\n")
	b.WriteString("# credentials in plain HTTP headers over your LAN/management network.\n")
	b.WriteString("# Use only in trusted, air-gapped or firewalled environments.\n")
	if s.License {
		b.WriteString("#\n")
		b.WriteString("# LICENSE NOTE:\n")
		b.WriteString("#   The license body must be the base64 encoding of your .lic file.\n")
		b.WriteString("#   To obtain it in bash:\n")
		b.WriteString("#     base64 -w0 veeam.lic\n")
		if s.LicenseB64 == "" {
			b.WriteString("#   The placeholder <BASE64_OF_YOUR_LIC> below must be replaced before running.\n")
		}
	}
	b.WriteString("# ===========================================================================\n")
	b.WriteString("set -euo pipefail\n\n")

	// Preamble — variables (single-quoted = literal-safe).
	baseURL := s.BaseURL
	if baseURL == "" {
		baseURL = "https://<VSA_IP>:9419"
	}
	fmt.Fprintf(&b, "BASE_URL=%q\n", baseURL)
	fmt.Fprintf(&b, "USERNAME=%q\n", s.Username)
	fmt.Fprintf(&b, "PASSWORD='%s'\n", strings.ReplaceAll(s.Password, "'", `'\''`))
	b.WriteString("Password=${PASSWORD}\n")
	if s.S3.Enabled {
		fmt.Fprintf(&b, "S3AccessKey='%s'\n", strings.ReplaceAll(s.S3.AccessKey, "'", `'\''`))
		fmt.Fprintf(&b, "S3SecretKey='%s'\n", strings.ReplaceAll(s.S3.SecretKey, "'", `'\''`))
	}
	if s.NodeExporter && s.NodeExporterUser != "" {
		fmt.Fprintf(&b, "NeBasicPass='%s'\n", strings.ReplaceAll(s.NodeExporterPass, "'", `'\''`))
	}
	fmt.Fprintf(&b, "API_VERSION=%q\n", s.APIVersion)
	b.WriteString("TOKEN=\"\"\n\n")

	// Auth helpers — token auto-refresh on 401.
	b.WriteString("# ---------------------------------------------------------------------------\n")
	b.WriteString("# Auth helpers — token auto-refresh on 401 (wiring can outlive the token).\n")
	b.WriteString("# ---------------------------------------------------------------------------\n")
	b.WriteString("get_token() {\n")
	b.WriteString("  TOKEN=$(curl -sk -X POST \"${BASE_URL}/api/oauth2/token\" \\\n")
	b.WriteString("    -H \"x-api-version: ${API_VERSION}\" -H 'Accept: application/json' \\\n")
	b.WriteString("    -H 'Content-Type: application/x-www-form-urlencoded' \\\n")
	b.WriteString("    --data-urlencode \"grant_type=Password\" \\\n")
	b.WriteString("    --data-urlencode \"username=${USERNAME}\" \\\n")
	b.WriteString("    --data-urlencode \"password=${PASSWORD}\" | jq -r '.access_token')\n")
	b.WriteString("}\n\n")

	// vbr METHOD URL [extra curl args...] — call, re-auth + retry once on HTTP 401.
	b.WriteString("vbr() {\n")
	b.WriteString("  local method=$1 url=$2; shift 2\n")
	b.WriteString("  local out code\n")
	b.WriteString("  out=$(curl -sk -w $'\\n%{http_code}' -X \"$method\" \"$url\" \\\n")
	b.WriteString("    -H \"x-api-version: ${API_VERSION}\" -H \"Authorization: Bearer ${TOKEN}\" -H 'Accept: application/json' \"$@\")\n")
	b.WriteString("  code=${out##*$'\\n'}; out=${out%$'\\n'*}\n")
	b.WriteString("  if [ \"$code\" = 401 ]; then\n")
	b.WriteString("    echo '    (token expired — re-authenticating)' >&2\n")
	b.WriteString("    get_token\n")
	b.WriteString("    out=$(curl -sk -w $'\\n%{http_code}' -X \"$method\" \"$url\" \\\n")
	b.WriteString("      -H \"x-api-version: ${API_VERSION}\" -H \"Authorization: Bearer ${TOKEN}\" -H 'Accept: application/json' \"$@\")\n")
	b.WriteString("    out=${out%$'\\n'*}\n")
	b.WriteString("  fi\n")
	b.WriteString("  printf '%s' \"$out\"\n")
	b.WriteString("}\n\n")

	// wait_session helper (uses vbr → re-auths on 401 mid-wait).
	b.WriteString("wait_session() {\n")
	b.WriteString("  local sid=$1 poll=${2:-10} timeout=${3:-1800} elapsed=0\n")
	b.WriteString("  while [ $elapsed -lt $timeout ]; do\n")
	b.WriteString("    sleep $poll\n")
	b.WriteString("    elapsed=$((elapsed + poll))\n")
	b.WriteString("    local resp result state\n")
	b.WriteString("    resp=$(vbr GET \"${BASE_URL}/api/v1/sessions/${sid}\")\n")
	b.WriteString("    result=$(echo \"$resp\" | jq -r '.result.result // empty')\n")
	b.WriteString("    state=$(echo  \"$resp\" | jq -r '.state // empty')\n")
	b.WriteString("    [ \"$result\" = 'Failed'  ] && { echo \"Session $sid FAILED\" >&2; exit 1; }\n")
	b.WriteString("    [ \"$result\" = 'Success' ] && return 0\n")
	b.WriteString("    [ \"$result\" = 'Warning' ] && return 0\n")
	b.WriteString("    [ \"$state\"  = 'Stopped' ] && return 0\n")
	b.WriteString("  done\n")
	b.WriteString("  echo \"Session $sid timed out after ${timeout}s\" >&2; exit 1\n")
	b.WriteString("}\n\n")

	// VIA-node wiring helpers — wait_node, find_managed_server, find_repository,
	// get_fingerprint, update_components, register_via_host, new_hardened_repo,
	// new_proxy. These mirror the per-node control flow in internal/wiring/wiring.go
	// and the JSON bodies in internal/veeam/veeam.go.
	b.WriteString("wait_node() {\n")
	b.WriteString("  local ip=$1 timeout=${2:-1800} elapsed=0\n")
	b.WriteString("  while [ $elapsed -lt $timeout ]; do\n")
	b.WriteString("    for port in 6160 443 22; do\n")
	b.WriteString("      if (exec 3<>\"/dev/tcp/$ip/$port\") 2>/dev/null; then exec 3>&-; return 0; fi\n")
	b.WriteString("    done\n")
	b.WriteString("    echo \"    ...$ip still installing/booting\" >&2\n")
	b.WriteString("    sleep 15; elapsed=$((elapsed + 15))\n")
	b.WriteString("  done\n")
	b.WriteString("  echo \"Node $ip not reachable within ${timeout}s\" >&2; exit 1\n")
	b.WriteString("}\n")
	b.WriteString("find_managed_server() {\n")
	b.WriteString("  local ip=$1\n")
	b.WriteString("  vbr GET \"${BASE_URL}/api/v1/backupInfrastructure/managedServers?nameFilter=${ip}&limit=10\" \\\n")
	b.WriteString("    | jq -r --arg n \"$ip\" '.data[]|select(.name==$n)|.id' | head -n1\n")
	b.WriteString("}\n")
	b.WriteString("find_repository() {\n")
	b.WriteString("  local name=$1\n")
	b.WriteString("  vbr GET \"${BASE_URL}/api/v1/backupInfrastructure/repositories?nameFilter=${name}&limit=50\" \\\n")
	b.WriteString("    | jq -r --arg n \"$name\" '.data[]|select(.name==$n)|.id' | head -n1\n")
	b.WriteString("}\n")
	b.WriteString("get_fingerprint() {\n")
	b.WriteString("  local ip=$1\n")
	b.WriteString("  local body; body=$(printf '{\"serverName\":\"%s\",\"type\":\"LinuxHost\"}' \"$ip\")\n")
	b.WriteString("  vbr POST \"${BASE_URL}/api/v1/connectionCertificate\" -H 'Content-Type: application/json' --data \"$body\" \\\n")
	b.WriteString("    | jq -r '.certificateUpload.certificate' | base64 -d | sha256sum | awk '{print toupper($1)}'\n")
	b.WriteString("}\n")
	b.WriteString("update_components() {\n")
	b.WriteString("  local host_id=$1\n")
	b.WriteString("  echo '    host components are updating - re-running update and retrying' >&2\n")
	b.WriteString("  local body; body=$(printf '{\"ids\":[\"%s\"]}' \"$host_id\")\n")
	b.WriteString("  local resp; resp=$(vbr POST \"${BASE_URL}/api/v1/backupInfrastructure/managedServers/updateComponents\" \\\n")
	b.WriteString("    -H 'Content-Type: application/json' --data \"$body\") || true\n")
	b.WriteString("  local sid; sid=$(printf '%s' \"$resp\" | jq -r '.id // empty')\n")
	b.WriteString("  [ -n \"$sid\" ] && wait_session \"$sid\" || true\n")
	b.WriteString("}\n")
	b.WriteString("register_via_host() {\n")
	b.WriteString("  local ip=$1 role=$2 pairing=$3\n")
	b.WriteString("  local id; id=$(find_managed_server \"$ip\")\n")
	b.WriteString("  if [ -n \"$id\" ]; then echo \"    $ip already registered - skipping add\" >&2; printf '%s' \"$id\"; return; fi\n")
	b.WriteString("  echo \"    adding Linux host $ip\" >&2\n")
	b.WriteString("  local fp; fp=$(get_fingerprint \"$ip\")\n")
	b.WriteString("  local body; body=$(printf '{\"type\":\"LinuxHost\",\"name\":\"%s\",\"description\":\"%s\",\"credentialsStorageType\":\"Certificate\",\"handshakeCode\":\"%s\",\"sshFingerprint\":\"%s\"}' \\\n")
	b.WriteString("    \"$ip\" \"$role\" \"$pairing\" \"$fp\")\n")
	b.WriteString("  local resp; resp=$(vbr POST \"${BASE_URL}/api/v1/backupInfrastructure/managedServers\" \\\n")
	b.WriteString("    -H 'Content-Type: application/json' --data \"$body\")\n")
	b.WriteString("  local sid; sid=$(printf '%s' \"$resp\" | jq -r '.id')\n")
	b.WriteString("  wait_session \"$sid\"\n")
	b.WriteString("  id=$(find_managed_server \"$ip\")\n")
	b.WriteString("  [ -n \"$id\" ] || { echo \"Failed to resolve managed server $ip after add\" >&2; exit 1; }\n")
	b.WriteString("  printf '%s' \"$id\"\n")
	b.WriteString("}\n")
	b.WriteString("new_hardened_repo() {\n")
	b.WriteString("  local host_id=$1 name=$2 path=$3 days=$4\n")
	b.WriteString("  local id; id=$(find_repository \"$name\")\n")
	b.WriteString("  if [ -n \"$id\" ]; then echo \"    repository $name already exists - skipping\" >&2; printf '%s' \"$id\"; return; fi\n")
	b.WriteString("  echo \"    creating hardened repository $name\" >&2\n")
	b.WriteString("  local body; body=$(printf '{\"type\":\"LinuxHardened\",\"name\":\"%s\",\"description\":\"\",\"hostId\":\"%s\",\"repository\":{\"path\":\"%s\",\"useFastCloningOnXFSVolumes\":true,\"makeRecentBackupsImmutableDays\":%s}}' \\\n")
	b.WriteString("    \"$name\" \"$host_id\" \"$path\" \"$days\")\n")
	b.WriteString("  local a resp sid msg\n")
	b.WriteString("  for a in 1 2 3; do\n")
	b.WriteString("    resp=$(vbr POST \"${BASE_URL}/api/v1/backupInfrastructure/repositories\" \\\n")
	b.WriteString("      -H 'Content-Type: application/json' --data \"$body\") && true\n")
	b.WriteString("    msg=$(printf '%s' \"$resp\" | jq -r '.message // empty')\n")
	b.WriteString("    sid=$(printf '%s' \"$resp\" | jq -r '.id // empty')\n")
	b.WriteString("    if [ -n \"$sid\" ]; then wait_session \"$sid\"; break; fi\n")
	b.WriteString("    if [ $a -lt 3 ] && echo \"$msg\" | grep -qi 'pending components update'; then\n")
	b.WriteString("      update_components \"$host_id\"; continue\n")
	b.WriteString("    fi\n")
	b.WriteString("    echo \"new_hardened_repo failed: $resp\" >&2; exit 1\n")
	b.WriteString("  done\n")
	b.WriteString("  printf '%s' \"$(find_repository \"$name\")\"\n")
	b.WriteString("}\n")
	b.WriteString("new_proxy() {\n")
	b.WriteString("  local host_id=$1\n")
	b.WriteString("  echo '    registering VMware backup proxy' >&2\n")
	b.WriteString("  local body; body=$(printf '{\"type\":\"ViProxy\",\"description\":\"\",\"server\":{\"hostId\":\"%s\",\"maxTaskCount\":4}}' \"$host_id\")\n")
	b.WriteString("  local a resp sid msg\n")
	b.WriteString("  for a in 1 2 3; do\n")
	b.WriteString("    resp=$(vbr POST \"${BASE_URL}/api/v1/backupInfrastructure/proxies\" \\\n")
	b.WriteString("      -H 'Content-Type: application/json' --data \"$body\") && true\n")
	b.WriteString("    msg=$(printf '%s' \"$resp\" | jq -r '.message // empty')\n")
	b.WriteString("    sid=$(printf '%s' \"$resp\" | jq -r '.id // empty')\n")
	b.WriteString("    if [ -n \"$sid\" ]; then wait_session \"$sid\"; return; fi\n")
	b.WriteString("    if [ $a -lt 3 ] && echo \"$msg\" | grep -qi 'pending components update'; then\n")
	b.WriteString("      update_components \"$host_id\"; continue\n")
	b.WriteString("    fi\n")
	b.WriteString("    echo \"new_proxy failed: $resp\" >&2; exit 1\n")
	b.WriteString("  done\n")
	b.WriteString("}\n\n")

	b.WriteString("echo '==> Authenticating'\n")
	b.WriteString("get_token\n\n")

	// Render each step.
	for _, st := range steps {
		if err := renderCurlStep(&b, st); err != nil {
			return "", err
		}
	}

	b.WriteString("echo '==> Done.'\n")
	return b.String(), nil
}

// curlEcho emits an echo progress line for a step comment (single-quoted).
func curlEcho(b *strings.Builder, comment string) {
	fmt.Fprintf(b, "echo '==> %s'\n", strings.ReplaceAll(comment, "'", `'\''`))
}

func renderCurlStep(b *strings.Builder, st Step) error {
	b.WriteString("# ---------------------------------------------------------------------------\n")
	b.WriteString("# " + st.Comment + "\n")
	b.WriteString("# ---------------------------------------------------------------------------\n")

	// High-level VIA-node wiring steps — delegate to helper functions.
	if st.Kind == "wireViaHr" {
		return renderCurlWireViaHr(b, st)
	}
	if st.Kind == "wireViaProxy" {
		return renderCurlWireViaProxy(b, st)
	}

	curlEcho(b, st.Comment)

	// configBackupRedirect is a special read-modify-write step.
	if st.Kind == "configBackupRedirect" {
		return renderCurlConfigBackupRedirect(b, st)
	}

	path := curlExpandPath(st.Path)

	switch st.Method {
	case "GET", "DELETE":
		fmt.Fprintf(b, "resp=$(vbr %s \"${BASE_URL}%s\")\n", st.Method, path)

	case "POST", "PUT":
		if st.Body != nil {
			// Build the body via an unquoted heredoc so ${vars} expand, then pass it.
			bodyBytes, err := json.MarshalIndent(st.Body, "", "  ")
			if err != nil {
				return fmt.Errorf("marshal body for %s %s: %w", st.Method, st.Path, err)
			}
			bodyStr := curlExpandBody(string(bodyBytes))
			b.WriteString("body=$(cat <<JSON\n")
			b.WriteString(bodyStr + "\n")
			b.WriteString("JSON\n")
			b.WriteString(")\n")
			fmt.Fprintf(b, "resp=$(vbr %s \"${BASE_URL}%s\" -H 'Content-Type: application/json' --data \"$body\")\n", st.Method, path)
		} else {
			fmt.Fprintf(b, "resp=$(vbr %s \"${BASE_URL}%s\" -H 'Content-Type: application/json' --data '{}')\n", st.Method, path)
		}
	}

	// Captures.
	if st.Kind == "certFingerprint" {
		fmt.Fprintf(b, "%s=$(echo \"$resp\" | jq -r '.certificateUpload.certificate' | base64 -d | sha256sum | awk '{print toupper($1)}')\n", st.Captures[0].Var)
	} else {
		for _, cap := range st.Captures {
			jqExpr := curlCapExpr(cap.Expr)
			fmt.Fprintf(b, "%s=$(echo \"$resp\" | jq -r '%s')\n", cap.Var, jqExpr)
		}
	}

	// Wait for async session.
	if st.WaitSession && st.WaitVar != "" {
		if st.OptionalWait {
			fmt.Fprintf(b, "( wait_session \"${%s}\" ) || echo \"optional step did not complete (continuing)\" >&2\n", st.WaitVar)
		} else {
			fmt.Fprintf(b, "wait_session \"${%s}\"\n", st.WaitVar)
		}
	}

	b.WriteString("\n")
	return nil
}

// renderCurlWireViaHr emits the high-level HR-node wiring block using the
// helper functions defined in the script preamble.
func renderCurlWireViaHr(b *strings.Builder, st Step) error {
	roleEsc := strings.ReplaceAll(st.Role, "'", `'\''`)
	fmt.Fprintf(b, "echo '==> Wire %s %s'\n", roleEsc, st.IP)
	fmt.Fprintf(b, "wait_node '%s'\n", st.IP)
	fmt.Fprintf(b, "%s=$(register_via_host '%s' '%s' '%s')\n",
		st.HostVar, st.IP, roleEsc,
		strings.ReplaceAll(st.Pairing, "'", `'\''`))
	fmt.Fprintf(b, "%s=$(new_hardened_repo \"${%s}\" '%s' '%s' '%d')\n",
		st.RepoVar, st.HostVar,
		strings.ReplaceAll(st.RepoName, "'", `'\''`),
		strings.ReplaceAll(st.RepoPath, "'", `'\''`),
		st.ImmutableDays)
	b.WriteString("\n")
	return nil
}

// renderCurlWireViaProxy emits the high-level proxy-node wiring block using the
// helper functions defined in the script preamble.
func renderCurlWireViaProxy(b *strings.Builder, st Step) error {
	roleEsc := strings.ReplaceAll(st.Role, "'", `'\''`)
	fmt.Fprintf(b, "echo '==> Wire %s %s'\n", roleEsc, st.IP)
	fmt.Fprintf(b, "wait_node '%s'\n", st.IP)
	fmt.Fprintf(b, "%s=$(register_via_host '%s' '%s' '%s')\n",
		st.HostVar, st.IP, roleEsc,
		strings.ReplaceAll(st.Pairing, "'", `'\''`))
	fmt.Fprintf(b, "new_proxy \"${%s}\"\n", st.HostVar)
	b.WriteString("\n")
	return nil
}

// renderCurlConfigBackupRedirect emits the read-modify-write pattern for
// /api/v1/configBackup using vbr + jq.
func renderCurlConfigBackupRedirect(b *strings.Builder, st Step) error {
	repoIDExpr := "${repo0_id}"
	if m, ok := st.Body.(map[string]any); ok {
		if v, ok2 := m["backupRepositoryId"].(string); ok2 {
			repoIDExpr = curlExpandPath(v)
		}
	}
	b.WriteString("cfg=$(vbr GET \"${BASE_URL}/api/v1/configBackup\")\n")
	fmt.Fprintf(b, "body=$(echo \"$cfg\" | jq --arg r \"%s\" '.backupRepositoryId=$r | .notifications.SNMPEnabled=false')\n", repoIDExpr)
	b.WriteString("resp=$(vbr PUT \"${BASE_URL}/api/v1/configBackup\" -H 'Content-Type: application/json' --data \"$body\")\n")
	b.WriteString("\n")
	return nil
}

// curlExpandPath rewrites shell-style $var references in a path/body to bash ${var}.
func curlExpandPath(path string) string {
	var out bytes.Buffer
	i := 0
	for i < len(path) {
		if path[i] == '$' {
			j := i + 1
			for j < len(path) && (isAlpha(path[j]) || path[j] == '_' || isDigit(path[j])) {
				j++
			}
			if j > i+1 {
				out.WriteString("${")
				out.WriteString(path[i+1 : j])
				out.WriteByte('}')
				i = j
				continue
			}
		}
		out.WriteByte(path[i])
		i++
	}
	return out.String()
}

// curlExpandBody expands $var_id references in a JSON body to ${var_id} for bash.
func curlExpandBody(body string) string {
	return curlExpandPath(body)
}

// curlCapExpr converts a capture expression to a jq path string.
func curlCapExpr(expr string) string {
	if expr == "__object__" || expr == "" {
		return "."
	}
	return "." + expr
}

func isAlpha(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
}

func isDigit(c byte) bool {
	return c >= '0' && c <= '9'
}
