package hypervisor

import (
	"strconv"
	"strings"
	"testing"
)

// TestNewWorkstationDefaults verifies that NewWorkstation fills in executable
// paths and VNCPortBase when they are left zero, and that it rejects configs
// missing required fields.
func TestNewWorkstationDefaults(t *testing.T) {
	t.Run("applies defaults", func(t *testing.T) {
		ws, err := NewWorkstation(WorkstationConfig{
			Host:      "win-host",
			Username:  "Administrator",
			Password:  "secret",
			VMBaseDir: `C:\VMs`,
			ISODir:    `C:\ISOs`,
			VNet:      "vmnet0",
		})
		if err != nil {
			t.Fatalf("NewWorkstation: %v", err)
		}
		wantDir := `C:\Program Files\VMware\VMware Workstation`
		if ws.cfg.InstallDir != wantDir {
			t.Errorf("InstallDir = %q, want %q", ws.cfg.InstallDir, wantDir)
		}
		wantVMRun := `C:\Program Files\VMware\VMware Workstation\vmrun.exe`
		if got := ws.vmRun(); got != wantVMRun {
			t.Errorf("vmRun() = %q, want %q", got, wantVMRun)
		}
		wantVdisk := `C:\Program Files\VMware\VMware Workstation\vmware-vdiskmanager.exe`
		if got := ws.vdiskManager(); got != wantVdisk {
			t.Errorf("vdiskManager() = %q, want %q", got, wantVdisk)
		}
		if ws.cfg.VNCPortBase != 5910 {
			t.Errorf("VNCPortBase = %d, want 5910", ws.cfg.VNCPortBase)
		}
		if ws.cfg.VNCHost != "win-host" {
			t.Errorf("VNCHost = %q, want %q", ws.cfg.VNCHost, "win-host")
		}
	})

	t.Run("explicit values preserved", func(t *testing.T) {
		ws, err := NewWorkstation(WorkstationConfig{
			Host:        "myhost",
			Username:    "u",
			Password:    "p",
			VMBaseDir:   `D:\VMs`,
			ISODir:      `D:\ISOs`,
			VNet:        "vmnet8",
			InstallDir:  `D:\VMware`,
			VNCPortBase: 6000,
			VNCHost:     "192.168.1.2",
		})
		if err != nil {
			t.Fatalf("NewWorkstation: %v", err)
		}
		if ws.cfg.InstallDir != `D:\VMware` {
			t.Errorf("InstallDir = %q, want %q", ws.cfg.InstallDir, `D:\VMware`)
		}
		if got := ws.vmRun(); got != `D:\VMware\vmrun.exe` {
			t.Errorf("vmRun() = %q, want %q", got, `D:\VMware\vmrun.exe`)
		}
		if ws.cfg.VNCPortBase != 6000 {
			t.Errorf("VNCPortBase = %d, want 6000", ws.cfg.VNCPortBase)
		}
		if ws.cfg.VNCHost != "192.168.1.2" {
			t.Errorf("VNCHost = %q, want %q", ws.cfg.VNCHost, "192.168.1.2")
		}
	})

	t.Run("missing Host", func(t *testing.T) {
		_, err := NewWorkstation(WorkstationConfig{
			VMBaseDir: `C:\VMs`,
			VNet:      "vmnet0",
		})
		if err == nil {
			t.Fatal("expected error for missing Host")
		}
	})

	t.Run("missing VMBaseDir", func(t *testing.T) {
		_, err := NewWorkstation(WorkstationConfig{
			Host: "host",
			VNet: "vmnet0",
		})
		if err == nil {
			t.Fatal("expected error for missing VMBaseDir")
		}
	})

	t.Run("missing VNet", func(t *testing.T) {
		_, err := NewWorkstation(WorkstationConfig{
			Host:      "host",
			VMBaseDir: `C:\VMs`,
		})
		if err == nil {
			t.Fatal("expected error for missing VNet")
		}
	})
}

// TestBuildVMX verifies the content of the .vmx template generated by
// buildVMX for various VMSpec configurations.
func TestBuildVMX(t *testing.T) {
	t.Run("basic single-disk VM", func(t *testing.T) {
		spec := VMSpec{
			Name:      "test-vm",
			CPUs:      4,
			MemoryMiB: 8192,
			Disks:     []int{100},
		}
		vmx := buildVMX("test-vm", spec, `C:\ISOs\veeam.iso`, "vmnet0", 5910)

		checks := []struct {
			desc string
			want string
		}{
			{"firmware=efi", `firmware = "efi"`},
			{"numvcpus", `numvcpus = "4"`},
			{"memsize", `memsize = "8192"`},
			{"one scsi0:0 block", `scsi0:0.present = "TRUE"`},
			{"disk0 filename", `scsi0:0.fileName = "disk0.vmdk"`},
			{"iso path", `sata0:1.fileName = "C:\ISOs\veeam.iso"`},
			{"ethernet0.vnet", `ethernet0.vnet = "vmnet0"`},
			{"vnc port", `RemoteDisplay.vnc.port = "5910"`},
			{"vnc enabled", `RemoteDisplay.vnc.enabled = "TRUE"`},
		}

		for _, c := range checks {
			if !strings.Contains(vmx, c.want) {
				t.Errorf("buildVMX missing %s: expected %q in:\n%s", c.desc, c.want, vmx)
			}
		}

		// Single-disk VM must NOT have scsi0:1.
		if strings.Contains(vmx, `scsi0:1.present`) {
			t.Errorf("buildVMX single-disk VM should not contain scsi0:1, but does")
		}
	})

	t.Run("multi-disk VM", func(t *testing.T) {
		spec := VMSpec{
			Name:      "vsa",
			CPUs:      8,
			MemoryMiB: 16384,
			Disks:     []int{256, 256},
		}
		vmx := buildVMX("vsa", spec, `C:\ISOs\veeam.iso`, "vmnet8", 5911)

		for i := 0; i < 2; i++ {
			wantPresent := `scsi0:` + strconv.Itoa(i) + `.present = "TRUE"`
			wantFile := `scsi0:` + strconv.Itoa(i) + `.fileName = "disk` + strconv.Itoa(i) + `.vmdk"`
			if !strings.Contains(vmx, wantPresent) {
				t.Errorf("missing %q", wantPresent)
			}
			if !strings.Contains(vmx, wantFile) {
				t.Errorf("missing %q", wantFile)
			}
		}

		if !strings.Contains(vmx, `numvcpus = "8"`) {
			t.Errorf("missing numvcpus=8")
		}
		if !strings.Contains(vmx, `memsize = "16384"`) {
			t.Errorf("missing memsize=16384")
		}
		if !strings.Contains(vmx, `ethernet0.vnet = "vmnet8"`) {
			t.Errorf("missing ethernet0.vnet=vmnet8")
		}
		if !strings.Contains(vmx, `RemoteDisplay.vnc.port = "5911"`) {
			t.Errorf("missing vnc port 5911")
		}
	})

	t.Run("default boot order is hdd,cdrom", func(t *testing.T) {
		spec := VMSpec{Name: "vm", CPUs: 2, MemoryMiB: 4096, Disks: []int{50}}
		vmx := buildVMX("vm", spec, "", "vmnet0", 5910)
		if !strings.Contains(vmx, `bios.bootOrder = "hdd,cdrom"`) {
			t.Errorf("expected default boot order hdd,cdrom in vmx:\n%s", vmx)
		}
	})
}
